In [1]:
import numpy as np

1d Array

In [3]:
np.zeros(3)

array([0., 0., 0.])

2d column Vector

In [5]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [7]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.zeros((3))

array([0., 0., 0.])

In [13]:
weights = np.zeros(3)
X = np.ones((3,3))

In [15]:
print(weights)
print(X)

[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
np.dot(weights,X)

array([0., 0., 0.])

In [21]:
import numpy as np
from sklearn.datasets import make_blobs
X, Y = make_blobs(n_samples=500, centers=2, n_features=2, random_state=10)
print(X.shape, Y.shape) 

(500, 2) (500,)


In [23]:
W = np.zeros(X.shape[0])
print(W)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [ ]:
import numpy as np
from sklearn.datasets import make_blobs

# Generate data
X, Y = make_blobs(n_samples=500, centers=2, n_features=2, random_state=10)
print(X.shape, Y.shape)  # Should output: (500, 2) (500,)

# Sigmoid function
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# Prediction function
def predict(X, weights):
    z = np.dot(X, weights)  
    return sigmoid(z)

# Binary cross-entropy loss
def loss(X, Y, weights):
    Y_ = predict(X, weights)
    cost = np.mean(-Y * np.log(Y_) - (1 - Y) * np.log(1 - Y_))
    return cost

# Gradient descent update
def update(X, Y, weights, learning_rate):
    Y_ = predict(X, weights)
    dw = np.dot(X.T, Y_ - Y)  
    m = X.shape[0]
    weights -= learning_rate * dw / float(m)
    return weights

# Training function
def train(X, Y, learning_rate=0.01, maxEpochs=500):
    # Add bias column
    ones = np.ones((X.shape[0], 1))
    X = np.hstack((ones, X))

    # Initialize weights
    weights = np.zeros(X.shape[1])

    for epoch in range(maxEpochs):
        weights = update(X, Y, weights, learning_rate)
        if epoch % 10 == 0:
            l = loss(X, Y, weights)
            print(f"Epoch {epoch}: Loss = {l:.4f}")

    return weights

# Train the logistic regression model
trained_weights = train(X, Y, learning_rate=0.01)

# Final weights
print("Trained Weights:", trained_weights)
